---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: production
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
      - name: init-permissions
        image: busybox:1.36
        command: ['sh', '-c', 'echo Setting up permissions']
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: log-exporter
        image: fluent/fluent-bit:2.1
      - name: app
        image: ghcr.io/home-assistant/home-assistant:2024.10.4
---
apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  namespace: production
spec:
  containers:
  - name: postgres
    image: postgres:16-alpine
    env:
    - name: POSTGRES_PASSWORD
      value: supersecret
  - name: redis-cache
    image: quay.io/keycloak/keycloak:26.0.0
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-job
spec:
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: backup
            image: ubuntu:25.10
            command:
            - /bin/bash
            - -c
            - echo "Running backup"
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Pod
metadata:
  name: monitoring-stack
spec:
  initContainers:
  - name: init-config
    image: alpine:3.19
  - name: init-azure
    image: mcr.microsoft.com/azure-cli:latest
  containers:
  - name: prometheus
    image: prom/prometheus:v2.45.0
  - name: grafana
    image: grafana/grafana:10.2.0
  - name: dotnet-app
    image: mcr.microsoft.com/dotnet/runtime:8.0
