apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: nginx
    image: nginx:latest
  - name: ubuntu
    image: ubuntu:25.10
  - name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
